### PR TITLE
Log when deprecated and new args are set at the same time

### LINKED ISSUE #1218: Notify admin not work: deprecated params are not used when new ones are set
I am using version 1.8.1, on November 24, I still received notifications in telegrams, but apparently after some update they stopped. That is, now on version 1.8.1 I do not receive telegram notifications. I also tried to set up email notifications and they don't come either.

Without changing anything in the configuration settings, I just switched to the master version and email notifications worked, but telegram notifications still do not work

### PR DESCRIPTION
**Pull request by paskal**
For example, when notify.telegram.token and telegram.token are both set but to different values, user might see "access denied" error in log on attempt to send telegram notification, thinking that notify.telegram.token value is used, when in fact it is ignored and only telegram.token is used.

New behavior is the same, ignoring the old param when new one is set, but issuing the error log message which explicitly tells the user about that.

Resolves #1218.

### CODE REVIEW

File: backend/app/cmd/cmd.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ type CommonOptionsCommander interface {
 	SetCommon(commonOpts CommonOpts)
 	Execute(args []string) error
 	HandleDeprecatedFlags() []DeprecatedFlag
+	FindDeprecatedFlagsCollisions() []DeprecatedFlag
```
Comment (umputun) [inline backend/app/cmd/cmd.go:25]: unlike others, this one has no default implementation in CommonOpts. I guess it may break other commands

File: backend/app/cmd/server.go [hunk 2]
```diff
@@ -321,7 +321,9 @@ func (s *ServerCommand) Execute(_ []string) error {
 	return nil
 }
 
-// HandleDeprecatedFlags sets new flags from deprecated returns their list
+// HandleDeprecatedFlags sets new flags from deprecated returns their list.
+// Returned list has DeprecatedFlag.Old and DeprecatedFlag.Version set, and DeprecatedFlag.New is optional
+// (as some entries are removed without substitute).
 func (s *ServerCommand) HandleDeprecatedFlags() (result []DeprecatedFlag) {
```
Comment (umputun) [inline backend/app/cmd/server.go:327]: maybe we don't need two methods to handle deprecated flags and should combine them?

**Review by umputun — CHANGES_REQUESTED** [review]

File: backend/app/cmd/server.go (hunk 2 above)
Comment (paskal) [reply backend/app/cmd/server.go:327]: I thought of combining them and differentiating the results by flag, but found out that the complexity of resulting function is too high and there really should be two functions: one reading old flags and setting new ones if old ones are still in use, and other just detecting collisions but sets nothing.

Comment (umputun) [reply backend/app/cmd/server.go:327]: well, i have nothing against having two functions inside the command to address the complexity, it makes sense. However I don't really see the reason the have two "entry points", i.e. interface functions doing a very similar thing. Maybe keep two and call conflict thingy from the handler without extending the interface?

**Review by umputun — APPROVED** [review]
LGTM
