### PR TITLE
Fix preview and comment work with proxified images

### LINKED ISSUE #1631: Problems with image caching (IMAGE_PROXY_CACHE_EXTERNAL)
I tried to use image caching and it doesn't work for me
```
- IMAGE_PROXY_CACHE_EXTERNAL=true
- IMAGE_PROXY_HTTP2HTTPS=true
```

Remark logs:
```
remark42  | 2023/04/28 01:14:07.922 [WARN]  {rest/httperrors.go:81 rest.SendErrorJSON} can't load picture from the comment - can't get image file for cached_images/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: can't get image stats for cached_images/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: stat var/pictures.staging/cached_images/84/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: no such file or directory - 400 (20) - myusername/github_myhash - /api/v1/comment?site=mysite - [rest/api/rest_private.go:136 api.(*private).createCommentCtrl]

remark42  | 2023/04/28 01:14:07.922 [INFO]  {logger/logger.go:134 logger.(*Middleware).Handler.func1.1} POST - /api/v1/comment?site=mysite - remark42.mysite.com - 0c8d1dc9c652 - 400 (467) - 358.164µs - {"title":"Comments","text":"![Image of my cat](https://placekitten.com/400/400)","locator":{"site":"mysite","url":"https://mysite.com/mypage.html"}}
```

Happened with any other images (not just https://placekitten.com/400/400), images from main domain e.g https://mysite.com/1.png, both HTTP (without redirect) and HTTP(s).

My setup is docker with nginx reverse proxy (nginx outside compose), umputun/remark42:latest, also tried building from master (logs from master).
All remote features, such as OAuth and Telegram notify, function properly, and normal image upload work too.

Remark didn't even create var/cached_images and var/pictures.staging/cached_images dirs. I tried to create manually with chmod/chown with 1001 (same as other dirs in var/), no luck.

Also it happned both in dev machine, and remote cloud, disable firewalls didn't help.

<details>
  <summary>http logs</summary>

```
POST /api/v1/comment?site=mysite HTTP/2
Host: remark42.mysite.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://remark42.mysite.com/web/iframe.html?host=https%3A%2F%2Fremark42.mysite.com&site_id=mysite&show_rss_subscription=false&url=https%3A%2F%2Fmysite.com%2Fmypage.html
X-XSRF-TOKEN: ...
Content-Type: application/json
Content-Length: 155
Origin: https://remark42.mysite.com
DNT: 1
Connection: keep-alive
Cookie: JWT=...; XSRF-TOKEN=...
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
TE: trailers

{"title":"Comments","text":"![Image of my cat](https://placekitten.com/400/400)","locator":{"site":"mysite","url":"https://mysite.com/mypage.html"}}


HTTP/2 400 Bad Request
server: nginx
date: Fri, 28 Apr 2023 07:25:11 GMT
content-type: application/json; charset=utf-8
content-length: 467
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers: Authorization
app-name: remark42
app-version: local-20230427T21:44:23
author: umputun
cache-control: no-cache, no-store, no-transform, must-revalidate, private, max-age=0
expires: Wed, 31 Dec 1969 18:00:00 CST
pragma: no-cache
ratelimit-limit: 1
ratelimit-remaining: 0
ratelimit-reset: 1
vary: Origin
x-rate-limit-duration: 1
x-rate-limit-limit: 0.50
x-rate-limit-request-forwarded-for: 127.0.0.1
x-rate-limit-request-remote-addr: 127.0.0.1
X-Firefox-Spdy: h2

{"code":20,"details":"can't load picture from the comment","error":"can't get image file for cached_images/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: can't get image stats for cached_images/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: stat var/pictures.staging/cached_images/84/e38d5bf8e071f20c8e6bb07ba5925359c84506be-c65ec743cf62a946d2c1ed2f64350d6961024e84: no such file or directory"}
```
</details>

<details>
  <summary>docker-compose (cleanup it to almost defaults, doenst help)</summary>

```
version: "2"

services:
  remark:
    build: .
    image: myhub/etc:remark42-master
    container_name: "remark42"
    hostname: "remark42"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "127.0.0.1:8080:8080"

    environment:
      - REMARK_URL=https://remark42.mysite.com
      - SITE=mysite
      - SECRET=
      - ADMIN_SHARED_ID=
      - ADMIN_SHARED_EMAIL=
      - DEBUG=true
      - IMAGE_PROXY_CACHE_EXTERNAL=true
      - IMAGE_PROXY_HTTP2HTTPS=true
      - AUTH_ANON=true
      - AUTH_GITHUB_CID=
      - AUTH_GITHUB_CSEC=
    volumes:
      - ./var:/srv/var
```
</details>

### PR DESCRIPTION
**Pull request by paskal**
Previously, image proxying through API was not tested. The test is added here.

Previously, proxied and local images were checked for presence in the storage before previewing or posting the comment. That logic resulted in an inability to post with an image when a proxy for images is enabled,  as proxied images are not downloaded to disk before the first time someone loads them, which could only happen after the user either previews or posts the message.

After this change, preview and post only checks the local images' presence and ignore the proxied ones.

Resolves #1631.

### CODE REVIEW

File: backend/app/store/image/image.go [hunk 1]
```diff
@@ -140,7 +140,10 @@ func (s *Service) Submit(idsFn func() []string) {
 }
 
 // ExtractPictures gets list of images from the doc html and convert from urls to ids, i.e. user/pic.png
-func (s *Service) ExtractPictures(commentHTML string) (ids []string) {
+// Proxied images are returned only if the flag is set: this is used in image check on post preview and load,
+// as proxied images have lazy loading and wouldn't be present on disk but still valid as they will be loaded
+// the first time someone requests them.
+func (s *Service) ExtractPictures(commentHTML string, returnProxied bool) (ids []string) {
```
Comment (umputun) [inline backend/app/store/image/image.go:146]: this new bool is used in multiple places and each place needs a comment about what this true/false means. How about making a small "enum" type with "image.DIRECT" and "image.PROXIED" values (consts)? Should make the api more readable

**Review by umputun — COMMENTED** [review]
A minor suggestion to make it more readable

File: backend/app/store/image/image.go (hunk 1 above)
Comment (paskal) [reply backend/app/store/image/image.go]: @umputun please take a look at the current version.

**Review by umputun — APPROVED** [review]
LGTM, thx
