### PR TITLE
fix leaking goroutines and add tests for them

### LINKED ISSUE #591: Leaking goroutines in proxy package tests
With the following changes in place I see leaking goroutines report:

```diff
diff --git a/backend/app/rest/proxy/image_test.go b/backend/app/rest/proxy/image_test.go
--- a/backend/app/rest/proxy/image_test.go
+++ b/backend/app/rest/proxy/image_test.go
@@ -16,6 +16,8 @@ import (
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/mock"
 	"github.com/stretchr/testify/require"
+	"go.uber.org/goleak"
+
 	"github.com/umputun/remark/backend/app/store/image"
 )
 
@@ -69,6 +71,7 @@ func TestImage_Replace(t *testing.T) {
 }
 
 func TestImage_Routes(t *testing.T) {
+	defer goleak.VerifyNone(t)
 	img := Image{HTTP2HTTPS: true, RemarkURL: "https://demo.remark42.com", RoutePath: "/api/v1/proxy"}
 
 	ts := httptest.NewServer(http.HandlerFunc(img.Handler))
```

Leaking goroutine test run report:

```go
=== RUN   TestImage_Routes
2020/02/08 18:02:56 WARN  can't get image http://127.0.0.1:61788/image/no-such-image.png - got unsuccessful response status 404 while fetching http://127.0.0.1:61788/image/no-such-image.png - 404 (18) - /?src=aHR0cDovLzEyNy4wLjAuMTo2MTc4OC9pbWFnZS9uby1zdWNoLWltYWdlLnBuZw== - [rest/proxy/image.go:118 proxy.Image.Handler]
2020/02/08 18:02:56 WARN  can't parse image url http://127.0.0.1:61788bad encoding - can parse url http://127.0.0.1:61788bad encoding: parse http://127.0.0.1:61788bad encoding: invalid port ":61788bad encoding" after host - 400 (18) - /?src=aHR0cDovLzEyNy4wLjAuMTo2MTc4OGJhZCBlbmNvZGluZw== - [rest/proxy/image.go:106 proxy.Image.Handler]
--- FAIL: TestImage_Routes (0.51s)
    image_test.go:221: http img request /image/img1.png
    image_test.go:233: http img request - not found /image/no-such-image.png
    leaks.go:78: found unexpected goroutines:
        [Goroutine 18 in state select, with net/http.(*persistConn).readLoop on top of the stack:
        goroutine 18 [select]:
        net/http.(*persistConn).readLoop(0xc0000b8c60)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2027 +0x999
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1575 +0xb0d
        
         Goroutine 19 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
        goroutine 19 [select]:
        net/http.(*persistConn).writeLoop(0xc0000b8c60)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2205 +0x123
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1576 +0xb32
        
         Goroutine 42 in state select, with net/http.(*persistConn).readLoop on top of the stack:
        goroutine 42 [select]:
        net/http.(*persistConn).readLoop(0xc0000b8fc0)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2027 +0x999
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1575 +0xb0d
        
         Goroutine 38 in state select, with net/http.(*persistConn).readLoop on top of the stack:
        goroutine 38 [select]:
        net/http.(*persistConn).readLoop(0xc0000b8ea0)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2027 +0x999
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1575 +0xb0d
        
         Goroutine 39 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
        goroutine 39 [select]:
        net/http.(*persistConn).writeLoop(0xc0000b8ea0)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2205 +0x123
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1576 +0xb32
        
         Goroutine 56 in state select, with net/http.setRequestCancel.func3 on top of the stack:
        goroutine 56 [select]:
        net/http.setRequestCancel.func3(0x0, 0xc000212360, 0xc00027a0a0, 0xc00026006c, 0xc0001f8420)
        	/usr/local/opt/go/libexec/src/net/http/client.go:321 +0xcf
        created by net/http.setRequestCancel
        	/usr/local/opt/go/libexec/src/net/http/client.go:320 +0x24b
        
         Goroutine 43 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
        goroutine 43 [select]:
        net/http.(*persistConn).writeLoop(0xc0000b8fc0)
        	/usr/local/opt/go/libexec/src/net/http/transport.go:2205 +0x123
        created by net/http.(*Transport).dialConn
        	/usr/local/opt/go/libexec/src/net/http/transport.go:1576 +0xb32
        ]
FAIL

Process finished with exit code 1
```

It might be a real problem or might be a problem with tests setup. I don't know how serious is it, I can investigate further or abandon that in case there is no harming effect.

### PR DESCRIPTION
**Pull request by paskal**
Resolves #591. Should be merged after #720, probably after rebase.

### CODE REVIEW

File: backend/app/cmd/server.go [hunk 1]
```diff
@@ -366,7 +369,8 @@ func (s *ServerCommand) newServerApp() (*serverApp, error) {
 	if err != nil {
 		return nil, errors.Wrap(err, "failed to make avatar store")
 	}
-	authenticator, err := s.makeAuthenticator(dataService, avatarStore, adminStore)
+	refreshCache := newAuthRefreshCache()
```
Comment (umputun) [inline backend/app/cmd/server.go:372]: I'd suggest to name it authRefreshCache because latter one it is hard to figure what refreshCache was about

**Comment by umputun** [comment]
note: it also has a conflict

**Comment by paskal** [comment]
@umputun conflict fixed and `refreshCache` became `authRefreshCache`.
